import { resolve, basename } from "node:path";
import { rm } from "node:fs/promises";
import type { StepContext } from "../context.js";
import { json } from "../fs/index.js";

export const REPO = "nauvalazhar/tskit";

/**
 * Downloads the TSKit template into `dir`, strips monorepo files,
 * rewrites package.json, and initializes a fresh git repo.
 */
export async function scaffoldTemplate(
  ctx: StepContext,
  dir: string,
): Promise<void> {
  // Download template (no git history)
  const { exitCode, stdout } = await ctx.run(
    `bunx --bun degit "${REPO}" "${dir}" --force`,
  );

  if (exitCode !== 0) {
    throw new Error(
      `Failed to download template from https://github.com/${REPO}\n\n${stdout}`,
    );
  }

  // Remove monorepo files and stale migrations (will be regenerated by db:generate)
  await rm(resolve(dir, "packages"), { recursive: true, force: true });
  await rm(resolve(dir, "src/database/migrations"), { recursive: true, force: true });
  const toRemove = ["pnpm-workspace.yaml", "turbo.json", "CLAUDE.md"];
  for (const file of toRemove) {
    try {
      await rm(resolve(dir, file), { force: true });
    } catch {
      // file may not exist
    }
  }

  // Rewrite package.json
  const name =
    (ctx.flag("name") as string) ||
    ctx.get<string>("projectName") ||
    basename(dir);
  const pkgPath = resolve(dir, "package.json");
  await json(pkgPath).merge({
    name,
    version: "0.0.1",
    private: true,
  });
  ctx.set("projectName", name);

  // Initialize fresh git repo
  await ctx.run(`cd "${dir}" && git init -q`);
}
